### ISSUE TITLE
Hybrid Schnorr pubkeys fail in script evalutation

### ISSUE THREAD

**Issue by dagurval** [dagurval/python-bitcoincash#7]
## Steps to reproduce

1) Revert commit https://github.com/dagurval/python-bitcoincash/commit/bfb64424af77b6eee3b9a81f12d1adb378c79289
2) `python3 -m unittest discover`

## Output
```
FAIL: test_script_schnorr (bitcoincash.tests.test_scripteval.Test_EvalScript)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dagurval/python-bitcoincash/bitcoincash/core/schnorr.py", line 208, in verify
    pubpoint = ser_to_point(pubkey)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dagurval/python-bitcoincash/bitcoincash/core/scripteval.py", line 168, in _CheckSig
    return bitcoincash.core.schnorr.verify(pubkey, sig, h)
ValueError: pubkey could not be parsed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dagurval/python-bitcoincash/bitcoincash/tests/test_scripteval.py", line 125, in test_script_schnorr
    VerifyScript(scriptSig, scriptPubKey, txSpend, 0, flags, amount = 0)
bitcoincash.core.scripteval.ArgumentsInvalidError: EvalScript: OP_CHECKSIG args invalid: pubkey error: pubkey could not be parsed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dagurval/python-bitcoincash/bitcoincash/tests/test_scripteval.py", line 128, in test_script_schnorr
    self.fail('Script FAILED: %r %r %r with exception %r' % (scriptSig, scriptPubKey, comment, err))
AssertionError: Script FAILED: CScript([x('d211631fdebf4c8376b3d169ef65a1987460eda43c3312e561b0226fa3069f68a68bac0dbf780f77dd60ff602c66186f1da2bb0a31f10187796242f48295ddbe01')]) CScript([x('0679be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8'), OP_CHECKSIG]) 'Schnorr P2PK with hybrid pubkey but no STRICTENC' with exception ArgumentsInvalidError('EvalScript: OP_CHECKSIG args invalid: pubkey error: pubkey could not be parsed')
```

**Comment by dagurval** [comment]
Pinging @markblundeberg in case you're not aware of the hybrid pubkey issue :-). This is from your Schnorr implementation I picked out of Electron Cash.

**Comment by markblundeberg** [comment]
Oh wow, ok you're using it for THAT! Yeah hybrid pubkeys suck, and it was me who added those test vectors even though they represent a basically unreal situation (hybrid pubkeys already became invalid since UAHF fork). The main idea with those tests was just to further demonstrate the point that "Really Schnorr works for any pubkey encoding, and the signatures don't care about encoding since the internal encoding is always compressed".

**Comment by dagurval** [comment]
Well yes I am! Thanks for the insight. With that, I think an way to solve this issue is to just raise an error when `VerifyScript` is called without `STRICTENC` in combination with a Schnorr signature.
